from abc import ABC, abstractmethod
class IPermissionService(ABC):
    @abstractmethod
    def index(self, params: dict) -> dict: ...
    @abstractmethod
    def store(self, data: dict, actor_id: str = '') -> object: ...
    @abstractmethod
    def edit(self, perm_id: str) -> object: ...
    @abstractmethod
    def update(self, perm_id: str, data: dict, actor_id: str = '') -> object: ...
    @abstractmethod
    def delete(self, perm_id: str) -> None: ...
    @abstractmethod
    def delete_selected(self, ids: list) -> int: ...
    @abstractmethod
    def sync_from_routes(self) -> int: ...
