from abc import ABC, abstractmethod


class IRoleService(ABC):
    @abstractmethod
    def index(self, params: dict) -> dict: ...
    @abstractmethod
    def store(self, data: dict, actor_id: str = '') -> object: ...
    @abstractmethod
    def edit(self, role_id: str) -> object: ...
    @abstractmethod
    def update(self, role_id: str, data: dict, actor_id: str = '') -> object: ...
    @abstractmethod
    def delete(self, role_id: str) -> None: ...
    @abstractmethod
    def delete_selected(self, ids: list) -> int: ...
    @abstractmethod
    def get_permissions(self, role_id: str, params: dict) -> dict: ...
    @abstractmethod
    def assign_permission(self, role_id: str, perm_id: str, actor_id: str = '') -> None: ...
    @abstractmethod
    def unassign_permission(self, role_id: str, perm_id: str) -> None: ...
    @abstractmethod
    def assign_selected(self, role_id: str, perm_ids: list) -> None: ...
    @abstractmethod
    def unassign_selected(self, role_id: str, perm_ids: list) -> None: ...
