from abc import ABC, abstractmethod


class IUserService(ABC):
    @abstractmethod
    def index(self, params: dict) -> dict: ...
    @abstractmethod
    def store(self, data: dict, actor_id: str = '') -> object: ...
    @abstractmethod
    def edit(self, user_id: str) -> object: ...
    @abstractmethod
    def update(self, user_id: str, data: dict, actor_id: str = '') -> object: ...
    @abstractmethod
    def delete(self, user_id: str) -> None: ...
    @abstractmethod
    def delete_selected(self, ids: list) -> int: ...
