# Generated by Django 6.0.6 on 2026-06-26 00:17

import apps.access.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=apps.access.models._uuid4_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=20, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=15)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('password_otp', models.CharField(blank=True, max_length=255, null=True)),
                ('password_otp_expires', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
                ('blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=255)),
                ('created_by', models.CharField(default='', max_length=36)),
                ('updated_by', models.CharField(default='', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(default=apps.access.models._uuid4_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=255, null=True)),
                ('created_by', models.CharField(default='', max_length=36)),
                ('updated_by', models.CharField(default='', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.CharField(default=apps.access.models._uuid4_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('guard_name', models.CharField(default='web', max_length=20)),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=255, null=True)),
                ('created_by', models.CharField(default='', max_length=36)),
                ('updated_by', models.CharField(default='', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'permissions',
                'indexes': [models.Index(fields=['name'], name='permissions__name'), models.Index(fields=['guard_name'], name='permissions__guard_name')],
            },
        ),
        migrations.CreateModel(
            name='RolesPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles_permissions', to='access.permission')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles_permissions', to='access.role')),
            ],
            options={
                'db_table': 'roles_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='access.RolesPermissions', through_fields=('role', 'permission'), to='access.permission'),
        ),
        migrations.CreateModel(
            name='UsersRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='users_roles', to='access.role')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='users_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_roles',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='access.UsersRoles', through_fields=('user', 'role'), to='access.role'),
        ),
    ]
