from abc import ABC, abstractmethod
class IAuthService(ABC):
    @abstractmethod
    def login(self, email: str, password: str) -> dict: ...
    @abstractmethod
    def register(self, data: dict) -> dict: ...
    @abstractmethod
    def logout(self, token: str) -> None: ...
    @abstractmethod
    def me(self, user) -> dict: ...
    @abstractmethod
    def request_reset(self, email: str) -> str: ...
    @abstractmethod
    def process_reset(self, email: str, otp: str, new_password: str) -> None: ...
